### ISSUE TITLE
CMD_REQUIRE_FREEURL_AUTHENTICATION=true config option not being respected

### ISSUE THREAD

**Issue by pirate** [hedgedoc/hedgedoc#1073]
**Description**

Setting `CMD_REQUIRE_FREEURL_AUTHENTICATION=true` appears to have no effect on 1.7.2. Unauthenticated/anonymous users in an incognito window are able to create freeurl notes with any alias and publish them.

**Expected behavior**

Neither creating notes with freeurls/aliases e.g. `/some-free-url` nor publishing them to e.g. `/s/some-free-url` should be allowed for anonymous / non-logged in users.

**To Reproduce**

Create this `docker-compose.yml`:
```yml
version: '2.4'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=hedgedoc
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=hedgedoc
    volumes:
      - ./db:/var/lib/postgresql/data

  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:1.7.2
    ports:
      - 3000:3000
    environment:
      - CMD_DB_URL=postgres://hedgedoc:hedgedoc@postgres:5432/hedgedoc
      - CMD_DEFAULT_PERMISSION=locked
      - CMD_ALLOW_FREEURL=true
      - CMD_ALLOW_ANONYMOUS=true
      - CMD_ALLOW_ANONYMOUS_EDITS=true
      - CMD_REQUIRE_FREEURL_AUTHENTICATION=true
    volumes:
      - ./uploads:/hedgedoc/public/uploads
```

```bash
# then start the containers
docker-compose up
```

1. open http://localhost:3000/some-free-url in an incognito window (not logged in)
2. a note is created with provided alias (expected behavior = permission denied)
3. click publish -> a note is published at http://localhost:3000/s/some-free-url (expected behavior = permission denied)

**Setup:**
 - Host OS: Docker
 - HedgeDoc version: `quay.io/hedgedoc/hedgedoc:1.7.2`
 
 **Relevant Code:**
  - https://github.com/hedgedoc/hedgedoc/blob/master/lib/config/environment.js#L32
  - https://github.com/hedgedoc/hedgedoc/blob/master/lib/web/note/util.js#L58
