### ISSUE TITLE
Can not find my docs after deleting history

### ISSUE THREAD

**Issue by boschkundendienst** [hedgedoc/hedgedoc#1199]
**Description**

I setup a selfhosted HedgeDoc instance on my private server. It works very well so far. I created a lot of documents containing tags and titles in the yaml meta data at the top of the documents.
When I am logged in and delete all my history, there is no way to ever find the documents again.
I tried with the search for tags for titles whatever - no result.

**To Reproduce**

I should be able to find my documents either bei entering a tag or a keyword somehow.

**Config**
I run it using docker-compose with this config:

```
networks:
  backend: {}
services:
  app:
    depends_on:
      database:
        condition: service_started
    environment:
      CMD_ALLOW_ANONYMOUS: "false"
      CMD_ALLOW_ANONYMOUS_EDITS: "false"
      CMD_ALLOW_EMAIL_REGISTER: "false"
      CMD_ALLOW_FREEURL: "false"
      CMD_ALLOW_GRAVATAR: "true"
      CMD_ALLOW_ORIGIN: '[''localhost''], [''my.public.domain'']'
      CMD_DB_URL: postgres://hedgedoc:averylongPostGresPassword@database:5432/hedgedoc
      CMD_DEFAULT_PERMISSION: private
      CMD_DOMAIN: my.public.domain
      CMD_EMAIL: "true"
      CMD_FORBIDDEN_NOTE_IDS: '[''robots.txt'', ''favicon.ico'', ''api'', ''build'',
        ''css'', ''docs'', ''fonts'', ''js'', ''uploads'', ''vendor'', ''views'']'
      CMD_HOST: 0.0.0.0
      CMD_IMAGE_UPLOAD_TYPE: filesystem
      CMD_LOGLEVEL: info
      CMD_PORT: '3000'
      CMD_PROTOCOL_USESSL: "true"
      CMD_REQUIRE_FREEURL_AUTHENTICATION: "true"
      CMD_SESSION_SECRET: averyLongSessionSecret
      CMD_URL_ADDPORT: "false"
      CMD_URL_PATH: ''
      CMD_USECDN: "false"
    image: quay.io/hedgedoc/hedgedoc:1.7.2
    networks:
      backend: null
    ports:
    - published: 3000
      target: 3000
    restart: always
    volumes:
    - uploads:/hedgedoc/public/uploads:rw
  database:
    environment:
      POSTGRES_DB: hedgedoc
      POSTGRES_PASSWORD: averylongPostGresPassword
      POSTGRES_USER: hedgedoc
    image: postgres:9.6-alpine
    networks:
      backend: null
    restart: always
    volumes:
    - database:/var/lib/postgresql/data:rw
version: '3'
volumes:
  database: {}
  uploads: {}
```

**Your Setup (please complete the following information):**
 - Host OS: [Oracle Linux]
 - NodeJS version [v12.22.1]
 - HedgeDoc version (Click "Version info" in the footer)
     - server [1.7.2]
     - client [Manjaro Linux (Chromium/Firefox latest]

**Additional context**

I don't know if I don't get the purpose of HedgeDoc or if I do something wrong but I think one should be able to find documents after deleting the history.

BTW if I do a complete deletion of the volumes and restore the database from backup, then re-login with the browser, my history is back!
