### ISSUE TITLE
Menu buttons to generate YAML metadata

### ISSUE THREAD

**Issue by boschkundendienst** [hedgedoc/hedgedoc#1215]
**Is your feature request related to a problem? Please describe.**

HedgeDoc supports YAML metadata and I use it a lot but I can not remember all the "YAML metas" so I either have to read the docs again or open an existing document to copy/paste YAML metas from there. This is not very effective.

**Describe the solution you'd like**

It would be nice, if there where 2 additional buttons in the menu:

- Button A **Create default YAML header**
- Button B **Create Slideshow YAML header**

Of course, one button with a drop-down might also work. 

**Button A** could then add something like this at the top of the document:

```
---
title: Sample YAML title
description: Symple YAML description
tags: examples, delimited
robots: noindex, nofollow
lang: en-us
dir: ltr
breaks: true

---
```

**Button B** could then add YAML for all possible Slideshow options available at the top of the document, e.g.:

```
---
title: Slideshow YAML Example
tags: presentation
slideOptions:
  theme: solarized
  # parallaxBackgroundImage: 'https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg'
  # Display controls in the bottom right corner
  controls: true

# Display a presentation progress bar
  progress: true

# Set default timing of 2 minutes per slide
  defaultTiming: 120

# Display the page number of the current slide
  slideNumber: true

# Push each slide change to the browser history
  history: false

# Enable keyboard shortcuts for navigation
  keyboard: true

# Enable the slide overview mode
  overview: true

# Vertical centering of slides
  center: true

# Enables touch navigation on devices with touch input
  touch: true

# Loop the presentation
  loop: true

# Change the presentation direction to be RTL
  rtl: false

# Randomizes the order of slides each time the presentation loads
  shuffle: false

# Turns fragments on and off globally
  fragments: true

# Flags if the presentation is running in an embedded mode,
# i.e. contained within a limited portion of the screen
  embedded: false

# Flags if we should show a help overlay when the questionmark
# key is pressed
  help: true

# Flags if speaker notes should be visible to all viewers
  showNotes: false

# Global override for autolaying embedded media (video/audio/iframe)
# - null: Media will only autoplay if data-autoplay is present
# - true: All media will autoplay, regardless of individual setting
# - false: No media will autoplay, regardless of individual setting
  autoPlayMedia: null

# Number of milliseconds between automatically proceeding to the
# next slide, disabled when set to 0, this value can be overwritten
# by using a data-autoslide attribute on your slides
#  autoSlide: 3000

# Stop auto-sliding after user input
  autoSlideStoppable: true

# Use this method for navigation when auto-sliding
  autoSlideMethod: Reveal.navigateNext

# Enable slide navigation via mouse wheel
  mouseWheel: false

# Hides the address bar on mobile devices
  hideAddressBar: true

# Opens links in an iframe preview overlay
  previewLinks: false

# Transition style
  transition: 'slide' 
# none/fade/slide/convex/concave/zoom

# Transition speed
  transitionSpeed: 'default'
# default/fast/slow

# Transition style for full page slide backgrounds
  backgroundTransition: 'fade'
# none/fade/slide/convex/concave/zoom

# Number of slides away from the current that are visible
  viewDistance: 3

# Parallax background image
  parallaxBackgroundImage: 'https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg'
# e.g. "'https://s3.amazonaws.com/hakim-static/reveal-js/reveal-parallax-1.jpg'"

# Parallax background size
  parallaxBackgroundSize: '"2100px 900px"'
# CSS syntax, e.g. "2100px 900px"

# Number of pixels to move the parallax background per slide
# - Calculated automatically unless specified
# - Set to 0 to disable movement along an axis
  parallaxBackgroundHorizontal: 20
  parallaxBackgroundVertical: 20
  #parallaxBackgroundHorizontal: null
  #parallaxBackgroundVertical: null
# The display mode that will be used to show slides
  display: 'block'
  
---
```

**Describe alternatives you've considered**
Copy/Paste from a sample file.

**Additional context**
This might also help others discover more features of HedgeDoc and how to use the YAML headers in the first place.
