### ISSUE TITLE
[Docker 1.8.2 Alpine] `uncaughtException: Cannot read property 'replace' of null` at startup

### ISSUE THREAD

**Issue by placaze** [hedgedoc/hedgedoc#1278]
**Description**
I just wanted to try out HedgeDoc 1.8.2 with the Docker Alpine image. The process crashs at startup:
```
2021/05/13 20:15:50 Waiting for: tcp://server.company.org:5432
2021/05/13 20:15:50 Connected to tcp://server.company.org:5432

> HedgeDoc@1.8.2 start /hedgedoc
> node app.js

2021-05-13T20:15:54.325Z error: 	uncaughtException: Cannot read property 'replace' of null
TypeError: Cannot read property 'replace' of null
    at new Sequelize (/hedgedoc/node_modules/sequelize/lib/sequelize.js:189:43)
    at Object.<anonymous> (/hedgedoc/lib/models/index.js:24:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/hedgedoc/app.js:27:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Config**
Here is my compose file for Docker Swarm (Jinja template):
```yaml
version: "3.4"

services:
  hedgedoc:
    image: artifactory.company.org/hedgedoc:1.8.2-alpine
    environment:
      - CMD_DB_URL="postgres://hedgedoc:password@server.company.org:5432/hedgedocdb"
      - CMD_DOMAIN="{{ hedgedoc_dns }}"
      - CMD_SESSION_SECRET=fc336b05bee5dfd3e20ef7ba3b4aa888b35d8be65a4fb276fa3710d77c8ed47e
    volumes:
      - "/mnt/docker-nfs/hedgedoc-data:/hedgedoc/public/uploads"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M
      update_config:
        delay: 2s
        order: stop-first
      labels:
        - traefik.enable=true
        - traefik.http.services.hedgedoc.loadbalancer.server.port=3000
        - traefik.http.routers.hedgedoc.rule=Host(`{{ hedgedoc_dns }}`)
        - traefik.http.routers.hedgedoc.entrypoints=https
        - traefik.http.routers.hedgedoc.tls=true
    networks:
      - company_network
    logging:
      options:
        max-size: "1M"
        max-file: "5"
    stop_grace_period: 5s

networks:
  company_network:
    external: true
```

**Your Setup**
 - Host OS: RHEL 7
 - Docker: 19.03
 - Hedgedoc: 1.8.2 (Alpine image)
