### ISSUE TITLE
Add Kubernetes typcial pod state probes

### ISSUE THREAD

**Issue by SISheogorath** [hedgedoc/hedgedoc#1568]
**Is your feature request related to a problem? Please describe.**
Kubernetes describes the Status of a Pod (a set of containers sharing a few namespaces) in with 3 probes: Startup probe, Readiness probe and Liveliness probe. Hedgedoc should provide endpoints to determine this status.

What do these endpoints say you might ask? The liveliness probes says whether the application itself has a problem. e.g. a path it tries to write to is not writeable, maybe it tries to write something to a local filesystem and it's full, etc. or in the positive case, the app itself is all good and alive.

The readiness probe goes one step further. It doesn't ask if the application itself is alive, but whether it's ready to take traffic and actually do work. When could this be in an error state? When the database is unavailable, uploads to a storage backend fail e.g. due to credentials, e.g. general external connectivity. Of course, this can also fail, when a liveliness probe fails or when the app is still running database migrations. When would this be considered OK? When the application is ready to process end-user requests.

And of course, the startup probe would check if the app has finished it's startup. While these probes are usually more targeted at e.g. Java apps, that take quite a while to start, it might still be an idea to use these for database migrations.

**Describe the solution you'd like**
The simplest and most universal solution would be to export 2 API endpoints  (`…/readiness`, `…/liveliness`) somewhere around the API, that describes these status by returning a HTTP status 200 if successful and >=400 if unsuccessful.

**Describe alternatives you've considered**
- No probes at all. Currently we just use the 200 status of the /status endpoint in 1.x. It's not great, but at least provides some insight.
- Implement probes as own programs. Another way to implement these probes is to make them own programs available inside the container. While this might be interesting, if we would run a bunch of services in a single container. For this setup, where we have one main app that is fully self-aware, an simple HTTP endpoint seems simpler to me.

**Additional context**
[Some more background information for these probes](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-setting-up-health-checks-with-readiness-and-liveness-probes)

**Comment by oskapt** [comment]
Exporting 2 paths is not the way we do things in Kubernetes, and it's also "liveness," not "liveliness." 

A check of `/status` is sufficient, if it can respond that the application is actually healthy and isn't just returning an HTML document that says `OK`.  If the `OK` is returned by a function within the application, from an internal status that determines all downstream components are OK, then this is the lightest-weight method for performing a health check.

Startup probes should check the same endpoint as the liveness or readiness probes, but with a longer delay before taking action (e.g. every 10s for 5 minutes). As soon as a startupProbe returns successful, then Kubernetes switches to using the other probes.

Readiness probes are used if the application can be bogged down doing something, during which time no traffic is sent to it, but it shouldn't be restarted. I don't think HedgeDoc will ever meet this requirement, so I'm only using a livenessProbe and a startupProbe, checking `/` on port 3000:

```
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
```

There's an argument that checking `/` every 10s is expensive, so a less expensive HTTPS endpoint would be helpful.

If you need any help with Kubernetes best practices, I'm available to assist.
