### ISSUE TITLE
uncaughtException: EISDIR

### ISSUE THREAD

**Issue by Lithimlin** [hedgedoc/hedgedoc#1880]
### Description

Somewhere, hedgedoc is attempting to open a directory as a file. However, the output is not verbose enough to make out which directory it is.

### Steps to reproduce

1. run `docker-compose up` with the required files

### Expected behaviour

Hedgedoc does not encounter the uncaught Exception

### Logs

```shell
...
hedgedoc_1     | [cont-init.d] 10-adduser: exited 0.
hedgedoc_1     | [cont-init.d] 30-config: executing... 
hedgedoc_1     | chown: changing ownership of '/config/config.json': Read-only file system
hedgedoc_1     | [cont-init.d] 30-config: exited 0.
hedgedoc_1     | [cont-init.d] 90-custom-folders: executing... 
hedgedoc_1     | [cont-init.d] 90-custom-folders: exited 0.
hedgedoc_1     | [cont-init.d] 99-custom-scripts: executing... 
hedgedoc_1     | [custom-init] no custom files found exiting...
hedgedoc_1     | [cont-init.d] 99-custom-scripts: exited 0.
hedgedoc_1     | [cont-init.d] done.
hedgedoc_1     | [services.d] starting services
hedgedoc_1     | [services.d] done.
hedgedoc_1     | /bin/sh: 1: git: not found
hedgedoc_1     | 2021-12-09T11:04:19.414Z warn: 	Overriding protocolUseSSL to 'true' as useSSL is enabled.
hedgedoc_1     | 2021-12-09T11:04:19.632Z error: 	uncaughtException: EISDIR: illegal operation on a directory, read
hedgedoc_1     | Error: EISDIR: illegal operation on a directory, read
hedgedoc_1     |     at Object.readSync (node:fs:723:3)
hedgedoc_1     |     at tryReadSync (node:fs:433:20)
hedgedoc_1     |     at Object.readFileSync (node:fs:479:19)
hedgedoc_1     |     at Object.<anonymous> (/opt/hedgedoc/app.js:50:17)
hedgedoc_1     |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
hedgedoc_1     |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
hedgedoc_1     |     at Module.load (node:internal/modules/cjs/loader:981:32)
hedgedoc_1     |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
hedgedoc_1     |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
hedgedoc_1     |     at node:internal/main/run_main_module:17:47
```

### Config

`docker-compose.yaml`, almost in full as I have no clue where the problem could actually lie:

```yaml
version: "3.5"                                                                  
services:                                                                       
  traefik:                                                                      
    image: traefik:latest                                                       
    command:                                                                    
      - --log.level=${LOG_LEVEL}                                             
      - --providers.docker                                                      
      - --providers.docker.exposedbydefault=false                               
      - --providers.file.directory=/configs/                                    
      - --entryPoints.web.address=:${HTTP_PORT}                                 
      - --entrypoints.web.http.redirections.entryPoint.to=websecure             
      - --entrypoints.web.http.redirections.entryPoint.scheme=https             
      - --entryPoints.websecure.address=:${HTTPS_PORT}  
    ports:                                                                      
      - ${HTTP_PORT}:80                                                         
      - ${HTTPS_PORT}:443                                                          
    volumes:                                                                    
      - /var/run/docker.sock:/var/run/docker.sock                               
      - ${DATA_DIR}/cert:/cert                                                  
      - ${DATA_DIR}/traefik_configs/:/configs                                   
      - ${DATA_DIR}/.metric_users:/userfiles/.metric_users   
    restart: ${RESTART_POLICY}

  hedgedoc-db:                                                                  
    image: postgres:13.5-alpine                                                 
    ports:                                                                      
      - 5432:5432                                                     
    environment:                                                                
      - POSTGRES_USER=${CMD_DB_USERNAME}                                        
      - POSTGRES_PASSWORD=${CMD_DB_PASSWORD}                                    
      - POSTGRES_DB=${CMD_DB_DATABASE}                                          
    volumes:                                                                    
      - database:/var/lib/postgresql/data                                       
    restart: ${RESTART_POLICY}                                                  
                                                                                
  hedgedoc:                                                                     
    image: linuxserver/hedgedoc:latest                                          
    ports:                                                                      
      - ${HEDGEDOC_PORT}:3000                                                   
    environment:                                                                
      - CMD_DB_HOST=hedgedoc-db                                                 
      - CMD_DB_DIALECT=postgres                                                 
      - CMD_DB_USERNAME                                                         
      - CMD_DB_PASSWORD                                                         
      - CMD_DB_DATABASE                                                         
      - CMD_DB_PORT                                                             
      - CMD_DOMAIN=${DOMAIN}                                                    
      - PGID=1000                                                               
      - PUID=1000                                                               
      - TZ                                                                      
    depends_on:                                                                 
      - hedgedoc-db                                                             
    volumes:                                                                    
      - ${DATA_DIR}/hedgedoc-config.json:/config/config.json:ro                 
      - ${DATA_DIR}/cert:/cert:ro                                               
      - uploads:/hedgedoc/public/uploads                                        
    labels:                                                                     
      - "traefik.enable=true"                                                   
      - "traefik.http.routers.hedgedoc.rule=Host(`${DOMAIN}`)"                  
      - "traefik.http.routers.hedgedoc.entryPoints=web"                         
      - "traefik.http.services.hedgedoc.loadbalancer.server.port=${HEDGEDOC_PORT}"          
      - "traefik.http.routers.hedgedoc-ssl.rule=Host(`${DOMAIN}`)"              
      - "traefik.http.routers.hedgedoc-ssl.entryPoints=websecure"               
      - "traefik.http.routers.hedgedoc-ssl.tls=true"                   
      - "traefik.http.routers.hedgedoc-ssl.service=hedgedoc"                    
      - "traefik.http.routers.metric-auth.rule=Host(`${DOMAIN}`) && (PathPrefix(`/metrics`) || PathPrefix(`/status`))"
      - "traefik.http.routers.metric-auth.middlewares=metric-auth"     
      - "traefik.http.routers.metric-auth.entryPoints=websecure"                
      - "traefik.http.routers.metric-auth.tls=true"                             
      - "traefik.http.middlewares.metric-auth.basicauth.usersfile=/userfiles/.metric_users"
    restart: ${RESTART_POLICY}                                                  
                                                                                
volumes:                                                                        
  database:                                                                     
  uploads:
```

`hedgedoc-config.json`:
```json
{                                                                               
  "production": {                                                                  
    "logLevel": "debug",                                                           
    "useSSL": true,                                                             
    "sslCertPath": "/cert/cert.crt",                                            
    "sslKeyPath": "/cert/cert.key",                                             
    "allowOrigin": [                                                            
      "localhost",                                                              
      "...",                                               
      "..."                                            
    ],                                                                          
    "sessionSecret": "...",
    "_permission-settings": "cut here"                                         
    "email": false,                                                             
    "ldap": {                                                                   
      "..."                                                    
    }                                                                           
  }                                                                             
}
```

### Your Setup

- Host OS: Debian 11
- NodeJS version: v16.13.1
- HedgeDoc version: linuxserver/hedgedoc:latest (1.9.2)

### Additional context

The config seems to be loaded as the session secret is set and other settings are also respected.
It does not seem to matter whether I make the `config.json` read-only or read-write.

My folder's structure is as follows:
```
.
├── cert
│   ├── cert.crt
│   └── cert.key
├── docker-compose.yaml
├── .env
├── hedgedoc-config.json
├── .metric_users
└── traefik_configs
    └── traefik_tls.yaml
```
(The variable `DATA_DIR` is set to `.`)
