### ISSUE TITLE
Authenticated requests to the public API are too slow

### ISSUE THREAD

**Issue by davidmehren** [hedgedoc/hedgedoc#1881]
### Description

HedgeDoc 2 currently manages to process about 4 authenticated requests to the public API per second.

### Steps to reproduce

1. Benchmark requests to `/api/v2/me`
2. Observe that 1000 requests take about 260 seconds.

### Expected behaviour

Requests take, I don't know, less than 50 ms?

### Your Setup

- Host OS: Fedora 35
- NodeJS version: 17.2
- HedgeDoc version: `develop`

**Comment by davidmehren** [comment]
Load testing with `artillery` results in
```
http.request_rate: .......................................... 10/sec
http.requests: .............................................. 600
http.codes.200: ............................................. 600
http.responses: ............................................. 600
http.response_time:
  min: ...................................................... 249
  max: ...................................................... 647
  median: ................................................... 347.3
  p95: ...................................................... 608
  p99: ...................................................... 632.8
  ```
  
  So we at least don't drop any requests at a rate of 10 per second. But 350 ms per API request is still too slow.
