### ISSUE TITLE
CSR won't load [domain]/cdn-cgi

### ISSUE THREAD

**Issue by arthur-trt** [hedgedoc/hedgedoc#2342]
### Description

CSR won't load [domain]/cdn-cgi

### Steps to reproduce

1. Install with docker-compose 
2. Access website

### Expected behaviour

Can't use hedgedoc because scipt doesn't load.

### Logs

```shell
Refused to load the script 'https://hedgedoc.[domain.tld]/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js' because it violates the following Content Security Policy directive: "script-src https://hedgedoc.[domain.tld]/build/ https://hedgedoc.[domain.tld]/js/ https://hedgedoc.[domain.tld]/config https://gist.github.com/ https://vimeo.com/api/oembed.json https://www.slideshare.net/api/oembed/2 'unsafe-inline' 'nonce-c2f3ecb4-8cc9-43bf-9a0e-07159e951222' 'sha256-81acLZNZISnyGYZrSuoYhpzwDTTxi7vC1YM4uNxqWaM='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

### Config

docker-compose.yml :
```yaml
-compose
version: '3'
services:
  database:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hedgedoc
    volumes:
      - /etc/hedgedoc/database:/var/lib/postgresql/data
    restart: always
  app:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: quay.io/hedgedoc/hedgedoc:1.9.3
    environment:
      - CMD_DB_URL=postgres://hedgedoc:password@database:5432/hedgedoc
      - CMD_DOMAIN=hedgedoc.[domain.tld]
      - CMD_URL_ADDPORT=false
      - CMD_PROTOCOL_USESSL=true
      - CMD_CSP_ALLOW_FRAMING=false
      - CMD_ALLOW_ORIGIN=['localhost', 'hedgedoc.[domain.tld]']
      - CMD_CSP_ENABLE=false // Add this because nothing works without
    volumes:
      - /etc/hedgedoc/uploads:/hedgedoc/public/uploads
    ports:
      - "3095:3000"
    restart: always
    depends_on:
      - database
volumes:
  database:
  uploads:
```

### Your Setup

- Host OS: Ubuntu 20.04
- Docker version 20.10.14, build a224086
- docker-compose version 1.29.2, build unknown
- HedgeDoc version: 1.9.3
- Caddy (reverse_proxy) v2.5.0 h1:eRHzZ4l3X6Ag3kUt8nj5IxATprhqKq/wToP7OHlXWA0=
