### ISSUE TITLE
hedgedoc-app-1 exited with code 1

### ISSUE THREAD

**Issue by sommerper** [hedgedoc/hedgedoc#2790]
### Description

Trying to get the app running on a Rarpberry Pi

### Steps to reproduce

Use an arm based computer
Use https://docs.hedgedoc.org/setup/docker/ `docker-compose` file.
Run `docker-compose up`

### Expected behaviour

app starts without errors

### Logs

```shell
[+] Running 2/2
 ⠿ Container hedgedoc-database-1  Recreated                                                          1.8s
 ⠿ Container hedgedoc-app-1       Recreated                                                          0.1s
Attaching to hedgedoc-app-1, hedgedoc-database-1
hedgedoc-database-1  |
hedgedoc-database-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
hedgedoc-database-1  |
hedgedoc-database-1  | 2022-10-27 16:10:49.825 UTC [1] LOG:  starting PostgreSQL 13.4 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit
hedgedoc-database-1  | 2022-10-27 16:10:49.825 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
hedgedoc-database-1  | 2022-10-27 16:10:49.825 UTC [1] LOG:  listening on IPv6 address "::", port 5432
hedgedoc-database-1  | 2022-10-27 16:10:49.831 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
hedgedoc-database-1  | 2022-10-27 16:10:49.839 UTC [21] LOG:  database system was shut down at 2022-10-27 16:07:38 UTC
hedgedoc-database-1  | 2022-10-27 16:10:49.848 UTC [1] LOG:  database system is ready to accept connections
hedgedoc-app-1       | exec /usr/local/bin/docker-entrypoint.sh: exec format error
hedgedoc-app-1 exited with code 0
hedgedoc-app-1 exited with code 1
hedgedoc-app-1 exited with code 1
hedgedoc-app-1 exited with code 1
hedgedoc-app-1 exited with code 1
hedgedoc-app-1 exited with code 1
```

### Config

docker-compose.yml
```
version: '3'
services:
  database:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hedgedoc
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
  app:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: quay.io/hedgedoc/hedgedoc:1.9.4
    environment:
      - CMD_DB_URL=postgres://hedgedoc:password@database:5432/hedgedoc
      - CMD_DOMAIN=localhost
      - CMD_URL_ADDPORT=true
    volumes:
      - uploads:/hedgedoc/public/uploads
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - database
volumes:
  database:
  uploads:
```

### Your Setup

- HedgeDoc version: 1.9.4
```
neofetch
       _,met$$$$$gg.          rst@public
    ,g$$$$$$$$$$$$$$$P.       -------------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) aarch64
 ,$$P'              `$$$.     Host: Raspberry Pi 4 Model B Rev 1.5
',$$P       ,ggs.     `$$b:   Kernel: 5.15.32-v8+
`d$$'     ,$P"'   .    $$$    Uptime: 96 days, 14 hours, 26 mins
 $$P      d$'     ,    $$P    Packages: 995 (dpkg)
 $$:      $$.   -    ,d$$'    Shell: zsh 5.8
 $$;      Y$b._   _,d$P'      Terminal: /dev/pts/1
 Y$$.    `.`"Y$$$$P"'         CPU: BCM2835 (4) @ 1.800GHz
 `$$b      "-.__              Memory: 1297MiB / 7811MiB
  `Y$$
   `Y$$.
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""
```
