### ISSUE TITLE
login not work

### ISSUE THREAD

**Issue by HyWell** [hedgedoc/hedgedoc#2804]
### Description

Login with email not working

### Steps to reproduce

Upgrade from codimd
1. nginx（SSL）config
```
# for socket.io (http upgrade)
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

# https server
server {
    listen 5000 http2 ssl;
    server_name hedgedoc.example.com;

    ssl_certificate fullchain.pem;
    ssl_certificate_key privkey.pem;
    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;

    if ($host != 'hedgedoc.example.com'){
        return 404;
    }


    location / {
        proxy_pass http://127.0.0.1:51003;
        proxy_redirect off;
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header X-Forwarded-Proto $scheme;        
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        
        # setup for image upload
        client_max_body_size 8192m;
        
        # adjust proxy buffer setting
        proxy_buffers 8 32k; 
        proxy_buffer_size 32k; 
        proxy_busy_buffers_size 64k;

        proxy_max_temp_file_size 8192m;
        
    }

    location /socket.io/ {
        proxy_pass http://127.0.0.1:51003;
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

    }


}
```
2. docker-compose config
```
version: "3"
services:
  database:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_USER=codimd
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=codimd
    volumes:
      - "database-data:/var/lib/postgresql/data"
    restart: always
  codimd:
          #image: hackmdio/hackmd:2.4.2
    image: quay.io/hedgedoc/hedgedoc:1.9.5
    environment:
      - CMD_DB_URL=postgres://codimd:password@database:5432/codimd
        # - CMD_AUTO_VERSION_CHECK=true
      - CMD_URL_ADDPORT=false
      - CMD_USECDN=false
      - CMD_ALLOW_ANONYMOUS=false
      - CMD_ALLOW_ANONYMOUS_EDITS=false
      - CMD_ALLOW_FREEURL=false
        # - CMD_ALLOW_ANONYMOUS_VIEWS=false
      - CMD_DEFAULT_PERMISSION=limited
        #- CMD_ALLOW_PDF_EXPORT=true
      - CMD_EMAIL=true
      - CMD_ALLOW_EMAIL_REGISTER=false
        #- CMD_ALLOW_ORIGIN=['hedgedoc.example.com']
      - CMD_PROTOCOL_USESSL=true
      - CMD_DOMAIN=hedgedoc.example.com:5000
    depends_on:
      - database
    ports:
      - "${MY_DOCKER_IP:-127.0.0.1}:51003:3000"
    volumes:
            # - upload-data:/home/hackmd/app/public/uploads
      - upload-data:/hedgedoc/public/uploads
    restart: always
volumes:
  database-data: {}
  upload-data: {}
```
3.  Login with wrong password
![image](https://user-images.githubusercontent.com/21263451/198945786-b166a93a-6cd3-4e92-abb3-836005b73776.png)
4. Login with correct password
![image](https://user-images.githubusercontent.com/21263451/198946043-ca420e50-4f89-4021-9ca9-e856ad35f08a.png)
Request & Response
![image](https://user-images.githubusercontent.com/21263451/198946328-9cede126-742d-48d8-ad3f-2abeef3c3704.png)

### Expected behaviour

Successfully logged in and displayed data

### Your Setup

- Host OS:  Ubuntu 18.04.6
- NodeJS version: docker
- HedgeDoc version: 1.9.5
