### ISSUE TITLE
Login does not generate request/traffic at all

### ISSUE THREAD

**Issue by fanyx** [hedgedoc/hedgedoc#2958]
### Description

Pressing the login button does not produce a login request

### Steps to reproduce

1. Open Sign in dialog
2. Input credentials (email & password)
3. Press Sign in
4. [...]

Nothing more happens.

Previously i have created the account in question by executing:
`docker-compose exec -it hedgedoc bin/manage_users --add fanyx@fanyx.xyz`

### Expected behaviour

A network request to my server shows up in the browser logs and either an successful or unsuccessful login response returns.

### Logs

```shell
No server logs.
No browser logs.
No nothing...
```

### Config

```shell
{
    "production": {
        "domain": "n.fanyx.xyz",
        "loglevel": "info",
        "db": {
            "username": "XXX",
            "password": "XXX",
            "database": "hedgedoc",
            "host": "db",
            "port": "5432",
            "dialect": "postgres"
        },
        "allowAnonymous": "false",
        "allowAnonymousEdits": "true",
        "allowFreeURL": "true",
        "requireFreeURLAuthentication": "true",
        "email": "true",
        "allowEmailRegister": "true"
    }
}
```

### Your Setup

- Host OS: Void 5.19.17_1 x86_64 GenuineIntel notuptodate hold FF
- NodeJS version: ?
- HedgeDoc version: 1.9.6

Additional information:
dockerized with `quay.io/hedgedoc/hedgedoc:1.9.6-alpine`, db running `postgres:13.4-alpine`

### Additional context

docker-compose config:

```
services:
  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:1.9.6-alpine
    container_name: hedgedoc_web
    restart: unless-stopped
    networks:
      - traefik_proxy
      - backend
    environment:
      - NODE_ENV=production
    volumes:
      - /var/docker/hedgedoc/uploads:/hedgedoc/public/uploads
      - /srv/docker/hedgedoc/config.json:/hedgedoc/config.json:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.hedgedoc.entrypoints: "https"
      traefik.http.routers.hedgedoc.rule: "Host(`n.fanyx.xyz`)"
  db:
    image: postgres:13.4-alpine
    container_name: hedgedoc_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=hedgedoc
      - POSTGRES_DB=hedgedoc
    networks:
      - backend
    volumes:
      - /var/docker/hedgedoc/database:/var/lib/postgresql/data

networks:
  traefik_proxy:
    name: traefik_proxy
  backend:
```
