### ISSUE TITLE
When printing, text color is always set to black ignoring custom CSS text color

### ISSUE THREAD

**Issue by silane** [hedgedoc/hedgedoc#3222]
### Description

When printing, text color is always set to black ignoring custom CSS text color.

### Steps to reproduce

1. Make a new note.
2. Write down bellow markdown.

```
<style>
    h1 {
        color: dodgerblue;
    }
</style>

# TEST

Hello <span style="color: red;">HedgeDoc</span> World.
```
3. We can see the color of text "TEST" and "HedgeDoc" are changed on the screen, but they turns all black when we print it even printer is set to color mode or printing to PDF.

### Expected behaviour

It should not reset all text color to black and respect the color set by CSS. It's especially annoying when converting to PDF.

### Your Setup

- Host OS: Arch Linux
- Docker Image: quay.io/hedgedoc/hedgedoc:1.9.6

### Additional context

I took a look inside the HTML and found that this issue is likely to caused by Bootstrap. HedgeDoc includes a style file `webpack:///node_modules/bootstrap/dist/css/dist/css/bootstrap.css` that contains the following CSS.

```css
@media print {
  *,
  *:before,
  *:after {
    color: #000 !important;
    text-shadow: none !important;
    background: transparent !important;
    -webkit-box-shadow: none !important;
    box-shadow: none !important;
  }
  /* ... */
}
```

The above CSS is causing this issue.

-----

This issue can be avoided adding `!important` to each CSS property but that's ugly, you know.
