### ISSUE TITLE
Higher than expected CPU use

### ISSUE THREAD

**Issue by reidprichard** [hedgedoc/hedgedoc#3421]
### Description

Monitoring my docker containers with cAdvisor, I noticed that hedgedoc-app is averaging ~10% CPU use in the background (not active connections). This is much higher than I would expect; other similar services are averaging 1-2%.

### Steps to reproduce

1. Install hedgedoc via a stack in Portainer
2. Observe high CPU use

### Expected behaviour

I would expect CPU use to be ~1% when I am not actively using hedgedoc.

### Config

```shell
version: '3'
services:
  database:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=hedgedoc
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
  app:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: quay.io/hedgedoc/hedgedoc:latest
    environment:
      - CMD_DB_URL=postgres://hedgedoc:pwd@database:5432/hedgedoc
      - CMD_DOMAIN=docs.example.com
      - CMD_PROTOCOL_USESSL=true
      - CMD_URL_ADDPORT=false
    volumes:
      - uploads:/hedgedoc/public/uploads
    ports:
      - "3002:3000"
    restart: "unless-stopped"
    depends_on:
      - database
volumes:
  database:
  uploads:
```

### Your Setup

- Host OS: Ubuntu 22.04
- NodeJS version: v16.19.1
- HedgeDoc version: v1.9.7

**Comment by reidprichard** [comment]
Okay, it seems the issue comes from very frequent healthchecks. I reduced the frequency from 5s to 1m, and it has dramatically reduced the CPU usage (~10% to ~3%):
```
version: '3'
services:
...
  app:
    # Make sure to use the latest release from https://hedgedoc.org/latest-release
    image: quay.io/hedgedoc/hedgedoc:latest
    healthcheck:
      interval: 1m
...
```

Is such an aggressive default healthcheck interval really needed? If so, it would be a useful addition to the documentation to mention that casual users should consider increasing the interval.
