### ISSUE TITLE
Move todo list checkboxes to top for multi-line tasks

### ISSUE THREAD

**Issue by Trayshar** [hedgedoc/hedgedoc#5907]
### Which part of the project should be enhanced?

Markdown TODO Lists

### Is your enhancement request related to a problem? Please describe.

On HedgeDoc 2 Alpha 3, it's hard to read multi-line todo list tasks because the checkbox appears at the bottom of the task. 

```markdown
- [ ] Lorem ipsum dolor sit amet,
consetetur sadipscing elitr,
sed diam nonumy eirmod tempor invidunt ut labore et dolore magna
```
renders as

![image](https://github.com/user-attachments/assets/1c02121d-5b98-43e3-a8eb-c00115370865)

### Describe the solution you'd like

The checkbox to appear at the top of the paragraph, like it does on GitHub:

- [ ] Lorem ipsum dolor sit amet,
consetetur sadipscing elitr,
sed diam nonumy eirmod tempor invidunt ut labore et dolore magna

### Describe alternatives you've considered

Deal with it :/

### Additional context

Adding this CSS fixes it:
```CSS
ul.contains-task-list > li.task-list-item:has(input.task-list-item-checkbox) {
    display: flex;
    align-items: baseline;
}
```
