### ISSUE TITLE
Config options for guest permissions in 2.0

### ISSUE THREAD

**Issue by InnayTool** [hedgedoc/hedgedoc#856]
What should be configurable in context of guest users?

It should be possible to set a maximum permission for guests.
Configuration options could be `deny` to disable guest access, `read` to allow only read on notes which enable it, `write` for allow writing in notes and `create` for creating new notes.
To prevent bots from creating notes with aliases (#754) an option like `createAlias` or separate config variable can be added.

**Comment by DerMolly** [comment]
So the idea would be to have something like this?

`HD_GUEST_ACCESS` with the options:
- `DENY`
- `READ`
- `WRITE`
- `CREATE`

And the extra option `HD_GUEST_NOTE_CREATION_ALIAS` with the values `true` and `false` (defaults to `true`)

**Comment by SISheogorath** [comment]
Personally I'm against to reintroduce this condig mess we had before.

Let's see if we can use structured data to represent what we try to achieve here and represent this with the variable names.

Idea:

```yaml
---
# … other config
features:
  guest_access:
    enabled: true
    default_note_permission: "deny"
    default_alias_permission: "deny"
  # …
```

Alternatively, maybe something more K8s rbac style:

```yaml
default_permissions:
  - group: guests
    apiGroup:
      - notes
    resources: []
    permissions:
      - read
      - write
      - create
   - group: authenticated_users
     apiGroup:
       - notes
       - aliases
      permissions:
       - create
       - read
       - write
      resources: []
```
