### ISSUE TITLE
Hide footer in presentation mode

### ISSUE THREAD

**Issue by AndiLeni** [hedgedoc/hedgedoc#88]
Hello,
I'd like to know wether it is possible to remove the footer in the presentation mode.

Regards
Andi

**Comment by SISheogorath** [comment]
You mean the lower area which refers to the original document and can optionally host disqus? Not right now, and I'm not sure why it would be needed as it is not visible unless you scroll down.

**Comment by AndiLeni** [comment]
Thanks for your answer. 
I didn't use it during a "real" presentation, but I am a little afraid that touching for example the Touchpad of my laptop would accidentally trigger a scrolldown. 
Also I guess it is simply not very useful, but again this is my personal opinion and if it is of any use I'd be glad to know.

**Comment by boschkundendienst** [comment]
Hiding this bar (by parameter like ?nobar) should be an option if possible. I am currently testing a presentation using slides on my iPhone using the frameless fullscreen browser. When holding it portrait mode the lower area is hidden and I can not even show it. When turning the phone into landscape mode the "lower area" shows at the bottom of the ios screen which makes no sense. It disappears when showing a high res video inside the presentation as video background but comes back on the next slide.

These are my current settings for the presentation:

```
---
type: slide
slideOptions: 
  controls: false
  controlsTutorial: true
  slideNumber: false
  progress: false
  hash: true
  loop: true
  showNotes: false
  transition: 'zoom'
  autoSlide: 6000
  hideInactiveCursor: true
  hideAddressBar: true
  autoSlideStoppable: false
  history: false
  preloadIframes: false
  
---
```

And this is the slide that removes the bar at the top (lower pane)

```
<!-- .slide: data-background-video="http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_60fps_normal.mp4" data-background-color="#000000" data-autoslide="10000" -->

## Video Backgrounds

`<!-- .slide: data-background-video="video.mp4,video.webm" -->`<br>Autoslide override with `<!-- data-autoslide="10000" -->`<br>You should set this to the length of your video if you want to play it entirely!

---
```

Btw. the same happens with Safari on iOS.
